project_id = "dfvrviuppfkqjpdyevfv"

[functions.verify-turnstile]
verify_jwt = false

[functions.turnstile-config]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.create-video-conversation]
verify_jwt = false

[functions.end-video-conversation]
verify_jwt = false
